<script src="<?= base_url('assets/bower_components/jquery/dist/jquery.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/bootstrap/dist/js/bootstrap.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/fastclick/lib/fastclick.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/bootbox/bootbox.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/bootbox/bootbox.locales.min.js') ?>"></script>
<script src="<?= base_url('assets/bower_components/toastr/toastr.min.js') ?>"></script>
<script src="<?= base_url('assets/dist/js/adminlte.min.js') ?>"></script>
<script src="<?= base_url('assets/dist/js/demo.js') ?>"></script>
<script src="<?= base_url('assets/dist/js/helper.js') ?>"></script>